
import type { Project, Experience, Education, Certificate } from './types';

export const author = {
  name: 'Amour Akowakou',
  title: 'Fullstack Developer',
  email: 'akowakou.dev@gmail.com',
  github: 'https://github.com/devakowakou',
  linkedin: 'https://linkedin.com/in/amour-akowakou-b3388127a',
  cv: '/pdf/amour_akowakou_cv_fullstack.pdf',
};

export const about = {
  intro:
    "Passion Fuels Purpose! Hi, I'm Amour Akowakou, a fullstack developer with a deep passion for building beautiful, functional, and user-centered digital experiences. I thrive on transforming complex problems into elegant solutions.",
  bio: "As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. My expertise spans across various technologies including Django, Node.js, Laravel, and React/Next.js. I am committed to continuous learning and applying my skills to create impactful software.",
  skills: {
    'Programming Languages': [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'PHP',
      'C#',
      'Go',
      'Ruby',
      'Swift',
      'Kotlin',
      'Rust',
      'C++',
      'Scala',
      'Elixir',
      'Dart',
      'Lua',
      'Perl',
      'MATLAB',
      'Groovy',
      'R',
    ],
    'Frameworks & Libraries': [
      'React',
      'Next.js',
      'Node.js',
      'Express',
      'Django',
      'Django REST Framework',
      'Ruby on Rails',
      'Laravel',
      'ASP.NET',
      'Vue',
      'Angular',
      'Svelte',
      'Framer Motion',
      'Tailwind CSS',
      'Flask',
      'FastAPI',
      'Symfony',
      'Spring',
      'jQuery',
      'SQLAlchemy',
    ],
    'Databases & Caching': [
      'PostgreSQL',
      'MongoDB',
      'MySQL',
      'Redis',
      'Firebase',
      'SQLite',
      'Oracle',
      'MariaDB',
      'SQLAlchemy',
    ],
    'DevOps & Tooling': [
      'Docker',
      'Kubernetes',
      'AWS',
      'Google Cloud',
      'Terraform',
      'Jenkins',
      'Ansible',
      'Git',
      'GraphQL',
      'Vite',
      'n8n',
      'Maven',
      'JWT',
      'OAuth2',
      'REST API',
      'WebSocket',
    ],
    IDEs: ['VS Code', 'IntelliJ IDEA', 'PyCharm', 'WebStorm', 'Vim', 'Eclipse'],
    'No-Code Tools': [
      'Webflow',
      'Bubble',
      'Zapier',
      'Airtable',
      'Notion',
      'Make',
      'Figma',
      'Adalo',
      'Glide',
      'Softr',
      'Odoo',
    ],
    'AI & Automation': [
      'ChatGPT',
      'Claude AI',
      'Gemini',
      'Groq AI',
      'OpenAI API',
      'Anthropic API',
      'Hugging Face',
      'LangChain',
      'LlamaIndex',
      'Pinecone',
      'Weaviate',
      'Chroma',
      'Gmail API',
      'n8n Workflows',
      'Zapier',
      'Make (Integromat)',
      'AI Resume Parsing',
      'Automated Notifications',
      'Computer Vision',
      'Natural Language Processing',
      'Machine Learning',
      'TensorFlow',
      'PyTorch',
      'Scikit-learn',
      'Pandas',
      'NumPy',
      'Jupyter',
    ],
  },
};

export const projects: Project[] = [
  // Backend & Full-Stack Projects
  {
    id: 'email-manager-n8n',
    title: 'Email Manager - n8n & React',
    description: 'A complete email management system combining n8n automation and a modern React web interface. Features automated email retrieval, AI-powered summaries using Groq (Llama 3.1-8B), JSON storage, and a responsive interface for reading and replying to emails. Includes CRON automation, REST APIs, and OAuth2 Gmail integration.',
    tags: ['n8n', 'React', 'Node.js', 'Docker', 'Gmail API', 'Groq AI'],
    imageUrl: '/images/email-manager.png',
    imageHint: 'email management automation system',
    repoUrl: 'https://github.com/devakowakou/n8n-email-workflow',
    demoUrl: '',
  },
  {
    id: 'hire-quick-api',
    title: 'Hire Quick - Recruitment Platform API',
    description: 'A comprehensive, high-performance recruitment platform API built with FastAPI. Features JWT authentication, role-based access control, async operations, AI-powered resume parsing, job-candidate matching, WebSocket notifications, and advanced analytics. Includes job management, application tracking, interview scheduling, and company profiles.',
    tags: ['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'JWT'],
    imageUrl: '/images/hire-quick.png',
    imageHint: 'recruitment platform api',
    repoUrl: ' https://github.com/devakowakou/hire-quick-app',
    demoUrl: '',
  },
  {
    id: 'student-management-system',
    title: 'Student Management System',
    description: 'A complete student management system built with Django REST Framework and Python. Features comprehensive student records management, course enrollment, grade tracking, attendance monitoring, fee management, teacher assignments, timetable scheduling, and parent portal. Includes RESTful APIs, authentication, and role-based access control for administrators, teachers, and students.',
    tags: ['Python', 'Django', 'PostgreSQL', 'React'],
    imageUrl: '/images/student-management.png',
    imageHint: 'student management system',
    repoUrl: 'https://github.com/devakowakou/studentapp',
    demoUrl: 'https://studentapp-xfmz.onrender.com',
  },
  {
    id: 'laverie-management',
    title: 'Laverie Management System',
    description: 'A comprehensive laundry management system built with Laravel and React. Features customer management, order tracking, payment processing, inventory management, real-time status updates, and automated notifications. Includes admin dashboard with analytics, employee management, and reporting tools.',
    tags: ['Laravel', 'React', 'MySQL', 'PHP'],
    imageUrl: '/images/laverie.png',
    imageHint: 'laundry management system',
    repoUrl: 'https://github.com/AKOWAKOU/frontoffice/tree/main',
    demoUrl: 'https://laverie-63yh.onrender.com',
  },
  {
    id: 'business-consulting',
    title: 'Business Consulting Website',
    description: 'A professional website for a business consulting firm built with Next.js. Features modern UI/UX design, service showcases, client testimonials, and contact forms. Optimized for performance and SEO with responsive design across all devices.',
    tags: ['Next.js', 'React', 'Tailwind CSS', 'Vercel'],
    imageUrl: '/images/business-consulting.png',
    imageHint: 'business consulting website',
    repoUrl: 'https://github.com/djiawou/business-consulting',
    demoUrl: 'https://businessconlting.vercel.app/',
  },
  {
    id: 'java-calculator',
    title: 'Java Calculator',
    description: 'A feature-rich calculator application built with Java using IntelliJ IDEA and Maven. Implements standard arithmetic operations with a clean GUI interface and follows object-oriented programming principles.',
    tags: ['Java', 'Maven', 'IntelliJ IDEA'],
    imageUrl: '/images/java-calculator.png',
    imageHint: 'java calculator application',
    repoUrl: 'https://github.com/devakowakou/java-calculator',
    demoUrl: '',
  },
  {
    id: 'shofy',
    title: 'Shofy',
    description: 'A complete MERN stack e-commerce solution with a focus on performance and user experience.',
    tags: ['MERN', 'React', 'MongoDB', 'Node.js', 'Express'],
    imageUrl: '/images/shofy.png',
    imageHint: 'MERN e-commerce',
    repoUrl: 'https://github.com/djiawou/shofy',
    demoUrl: 'https://shofy-omega.vercel.app/',
  },
  {
    id: 'tutor-match',
    title: 'Tutor-Student Matchmaking System',
    description: 'A MERN stack application designed to connect students with qualified tutors based on their learning needs.',
    tags: ['MERN', 'React', 'MongoDB', 'Node.js', 'Express'],
    imageUrl: '/images/studena.png',
    imageHint: 'online tutoring platform',
    repoUrl: 'devakowakou/studena-matchmaking',
    demoUrl: 'https://frontend-two-sable-30.vercel.app/',
  },
  {
    id: 'dema-services',
    title: 'Website Dema-Service (Odoo)',
    description: 'Dema-Services is a luxury event planning company specializing in weddings, private celebrations, and brand experiences. Founded by Precious Thamaga-Mazibuko, a prominent wedding planner and event designer, the company has been creating unforgettable events since 2011.',
    tags: ['Django', 'React', 'PostgreSQL', 'SaaS','Odoo'],
    imageUrl: '/images/dema-services.png',
    imageHint: 'event planning website',
    repoUrl: 'https://github.com/devakowakou/dema-services',
    demoUrl: 'https://www.demaservices.cm',
  },
  {
    id: 'sublime-votre',
    title: ' Website Sublime Votre (Odoo)',
    description: 'Sublime Votre is a beauty salon offering a wide range of services such as haircuts, pedicures, manicures, facials, eyelash extensions, makeup, body scrubs, and lipocavitation treatments. The salon focuses on providing a personalized and luxurious experience with high-quality products and innovative techniques.',
    tags: ['Laravel', 'Vue.js', 'MySQL','Odoo'],
    imageUrl: '/images/sublime-votre.png',
    imageHint: 'beauty salon website',
    repoUrl: 'https://github.com/devakowakou/sublime-votre',
    demoUrl: 'https://www.sublimevotre.ca',
  },
  {
    id: 'csi',
    title: 'Website CSI ',
    description: 'CSI is a website Developed for me of a my client. ',
    tags: ['Node.js', 'Express', 'MongoDB', 'React','Odoo'],
    imageUrl: '/images/csi.png',
    imageHint: 'client project website',
    repoUrl: 'https://github.com/devakowakou/csi',
    demoUrl: 'https://www.csi-moulins.fr',
  },
  {
    id: 'afrykanna',
    title: 'Website Afrykanna ',
    description: 'Afrykanna is a website Developed for me of a my client. ',
    tags: ['Node.js', 'Express', 'MongoDB', 'React','Odoo'],
    imageUrl: '/images/afrykanna.png',
    imageHint: 'client project website',
    repoUrl: 'https://github.com/devakowakou/afrykanna',
    demoUrl: 'https://afrykanna.com',
  },
  {
    id: 'numpharm',
    title: 'Website Pharmacie(Odoo)',
    description: 'NumPharm is an online pharmacy that operates primarily in Alberta,offering fast, free same-day prescription delivery. They provide servicessuch as prescription uploads, prescription transfers,and medication packaging for convenience. nuPharma aims to simplify the pharmacy experience by offering virtual consultations and easy access through an app.',
    tags: ['React','Odoo'],
    imageUrl: '/images/numpharm.png',
    imageHint: 'online pharmacy website',
    repoUrl: 'https://github.com/devakowakou/numpharm',
    demoUrl: 'https://numpharm.org/',
  },
  {
    id: 'philjohn-tech',
    title: 'Website PHILJOHN TECH (Odoo)',
    description: 'Philjohn Technologies is an innovative company based in Douala, Cameroon, specializing in providing a wide range of IT solutions and services. Their offerings cover areas like IT consulting, enterprise applications development, infrastructure maintenance,cybersecurity, and digital transformation managemen.',
    tags: ['Next.js', 'Framer Motion', 'Tailwind CSS','Odoo'],
    imageUrl: '/images/philjohn-tech.png',
    imageHint: 'tech company website',
    repoUrl: 'https://github.com/devakowakou/philjohn-tech',
    demoUrl: 'https://www.philjohntech.com/',
  },
  
  // Frontend Projects
  {
    id: 'niyas-store',
    title: 'Niyas Store',
    description: 'An elegant and modern e-commerce platform with a clean user interface and a seamless shopping experience.',
    tags: ['Next.js', 'E-commerce', 'Tailwind CSS', 'Vercel'],
    imageUrl: '/images/niyas-store.png',
    imageHint: 'e-commerce website',
    repoUrl: 'https://github.com/djiawou/niyas-store',
    demoUrl: 'https://niyas-store.vercel.app',
  },
  {
    id: 'claire-net',
    title: 'Claire Net',
    description: 'A professional website for a cleaning service company, designed to attract clients and showcase their services.',
    tags: ['Next.js', 'Landing Page', 'Services', 'Vercel'],
    imageUrl: '/images/claire-net.png',
    imageHint: 'cleaning service website',
    repoUrl: 'https://github.com/djiawou/claire-net',
    demoUrl: 'https://claire-net.vercel.app',
  },
   {
    id: 'gocart',
    title: 'GoCart',
    description: 'A modern and feature-rich e-commerce application for a seamless online shopping experience.',
    tags: ['Next.js', 'E-commerce', 'Tailwind CSS'],
    imageUrl: '/images/gocart.png',
    imageHint: 'e-commerce app',
    repoUrl: 'https://github.com/djiawou/gocart',
    demoUrl: 'https://gocart-lac.vercel.app/',
  },
];

export const experiences: Experience[] = [
  {
    id: 'exp1',
    company: 'RightCom',
    role: 'Back End Developer',
    date: 'Oct 2024 - Jun 2025',
    description: [
      'Contributed to the development of RightSurvey, a large-scale enterprise survey platform.',
      'Engineered and optimized RESTful APIs using Python with Flask and Falcon frameworks.',
      'Developed microservices and APIs with Node.js to support various application features.'
    ],
    technologies: ['Python', 'Flask', 'Node.js', 'Express', 'PostgreSQL', 'Docker', 'Git', 'VS Code'],
  },
  {
    id: 'exp2',
    company: 'PHILJOHN TECH',
    role: 'Freelance Odoo Consultant',
    date: 'Jan 2024 - Present',
    description: [
      'Managed end-to-end Odoo ERP integration, customization, and maintenance for a diverse portfolio of international clients.',
      'Developed custom Python modules to automate key business processes, improving operational efficiency.',
      'Built an automated email management system using n8n, React, and Gmail API with AI-powered summaries.',
      'Provided comprehensive user training and continuous technical support to ensure smooth adoption.'
    ],
    technologies: ['Odoo', 'Python', 'PostgreSQL', 'JavaScript', 'XML', 'Docker', 'Linux', 'Git', 'PyCharm', 'n8n', 'React'],
  },
  {
    id: 'exp3',
    company: 'TEC-SARL',
    role: 'PHP-Symfony Developer',
    date: 'Feb 2023 - Jun 2023',
    description: [
      'Designed and deployed a company-wide LAN network, including Cisco access point configuration.',
      'Implemented a client-server VoIP solution to modernize internal communications.',
      'Led the development of the corporate website using the PHP Symfony framework.'
    ],
    technologies: ['PHP', 'Symfony', 'MySQL', 'JavaScript', 'Docker', 'Git', 'VS Code'],
  },
   {
    id: 'exp4',
    company: 'PHILJOHN TECH',
    role: 'Web Developer',
    date: 'Jan 2023 - Dec 2023',
    description: [
      'Oversaw the full development lifecycle and ongoing maintenance of the numpharm.org web platform.',
      'Designed and deployed scalable RESTful APIs using Python and the Django REST Framework.',
      'Created custom Python scripts for complex business data extraction and analysis, enabling data-driven decisions.'
    ],
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Docker', 'Git', 'VS Code'],
  },
];

export const education: Education[] = [
  {
    id: 'edu1',
    school: 'ESGIS',
    degree: "Bachelor's Degree in Software Architecture",
    date: '2022 - 2025',
    location: 'Cotonou',
    country: 'Bénin',
    website: 'esgis.bj',
    description: [
      'Acquired strong foundations in software engineering, algorithms, and object-oriented programming.',
      'Studied and applied software architecture patterns such as MVC, microservices, and event-driven design.',
      'Designed and implemented web and mobile applications using modern frameworks and tools.',
      'Worked with SQL and NoSQL databases to design, optimize, and manage complex data structures.',
      'Learned DevOps practices including CI/CD pipelines, Docker, and cloud deployment strategies.',
      'Gained experience in Agile project management, UML modeling, and technical documentation.',
      'Developed skills to build scalable, secure, and maintainable software solutions.'
    ],
  }
];

export const certificates: Certificate[] = [
    {
      id: 'cert1',
      title: 'Certified Health Data Analyst (CHDA)',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://www.freecodecamp.org/certification/fcca4b4305c-258a-4998-a9ae-138c2d98f126/data-analysis-with-python-v7',
      skills: ['Python', 'Pandas', 'NumPy', 'Matplotlib'],
    },
    {
      id: 'cert2',
      title: 'Back End Development and APIs',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://www.freecodecamp.org/certification/fcc0daddbae-4b65-4434-9520-66b3d5c1596b/back-end-development-and-apis',
      skills: ['Node.js', 'Express', 'APIs', 'MongoDB'],
    },
    {
      id: 'cert3',
      title: 'Responsive Designe',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://www.freecodecamp.org/certification/fcca4b4305c-258a-4998-a9ae-138c2d98f126/responsive-web-design',
      skills: ['HTML', 'CSS', 'Flexbox', 'CSS Grid','Jquery'],
    },
    {
      id: 'cert4',
      title: 'Relational Databases',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://www.freecodecamp.org/certification/fcc0daddbae-4b65-4434-9520-66b3d5c1596b/relational-database-v8',
      skills: ['Bash', 'PostgreSQL', 'Git'],
    },
    {
      id: 'cert5',
      title: 'Scientific Computing with Python',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://freecodecamp.org/certification/fcca4b4305c-258a-4998-a9ae-138c2d98f126/scientific-computing-with-python-v7',
      skills: ['Test Cases', 'PostgreSQL', 'Scientific Computing','Python'],
    },
    {
      id: 'cert6',
      title: 'Data Visualization',
      issuer: 'FreeCodeCamp',
      date: '2024',
      url: 'https://www.freecodecamp.org/certification/fcc0daddbae-4b65-4434-9520-66b3d5c1596b/data-visualization',
      skills: ['Git', 'PostgreSQL', 'JavaScript','Python'],
    },
  ];
