export const skillIcons: Record<string, string> = {
  JavaScript: '/icons/javascript.svg',
  TypeScript: '/icons/typescript.svg',
  Python: '/icons/python.svg',
  Java: '/icons/java.svg',
  'C#': '/icons/csharp.svg',
  Go: '/icons/go.svg',
  Ruby: '/icons/ruby.svg',
  Swift: '/icons/swift.svg',
  Kotlin: '/icons/kotlin.svg',
  Rust: '/icons/rust.svg',
  'C++': '/icons/cplusplus.svg',
  Scala: '/icons/scala.svg',
  Elixir: '/icons/elixir.svg',
  Dart: '/icons/dart.svg',
  PHP: '/icons/php.svg',
  React: '/icons/react.svg',
  'Next.js': '/icons/nextjs.svg',
  'Node.js': '/icons/nodejs.svg',
  Express: '/icons/express.svg',
  Django: '/icons/django.svg',
  'Ruby on Rails': '/icons/rails.svg',
  Laravel: '/icons/laravel.svg',
  'ASP.NET': '/icons/dotnet.svg',
  Vue: '/icons/vue.svg',
  Angular: '/icons/angular.svg',
  Svelte: '/icons/svelte.svg',
  PostgreSQL: '/icons/postgresql.svg',
  MongoDB: '/icons/mongodb.svg',
  MySQL: '/icons/mysql.svg',
  Redis: '/icons/redis.svg',
  'Tailwind CSS': '/icons/tailwindcss.svg',
  'Framer Motion': '/icons/framer.svg',
  Docker: '/icons/docker.svg',
  Kubernetes: '/icons/kubernetes.svg',
  'Google Cloud': '/icons/google-cloud.svg',
  AWS: '/icons/aws.svg',
  Git: '/icons/git.svg',
  Terraform: '/icons/terraform.svg',
  Jenkins: '/icons/jenkins.svg',
  Ansible: '/icons/ansible.svg',
  GraphQL: '/icons/graphql.svg',
  Firebase: '/icons/firebase.svg',
  Vite: '/icons/vite.svg',
  Lua: '/icons/lua.svg',
  Perl: '/icons/perl.svg',
  MATLAB: '/icons/matlab.svg',
  Groovy: '/icons/groovy.svg',
  R: '/icons/r.svg',
  Flask: '/icons/flask.svg',
  FastAPI: '/icons/fastapi.svg',
  Symfony: '/icons/symfony.svg',
  Spring: '/icons/spring.svg',
  jQuery: '/icons/jquery.svg',
  SQLite: '/icons/sqlite.svg',
  Oracle: '/icons/oracle.svg',
  MariaDB: '/icons/mariadb.svg',
  'VS Code': '/icons/vscode.svg',
  'IntelliJ IDEA': '/icons/intellij-idea.svg',
  PyCharm: '/icons/pycharm.svg',
  WebStorm: '/icons/webstorm.svg',
  Vim: '/icons/vim.svg',
  Webflow: '/icons/webflow.svg',
  Bubble: '/icons/bubble.svg',
  Zapier: '/icons/zapier.svg',
  Airtable: '/icons/airtable.svg',
  Notion: '/icons/notion.svg',
  Make: '/icons/make.svg',
  Figma: '/icons/figma.svg',
  Adalo: '/icons/adalo.svg',
  Glide: '/icons/glide.svg',
  Softr: '/icons/softr.svg',
  Vercel: '/icons/vercel.svg',
  'E-commerce': '/icons/shopping-cart.svg',
  'Landing Page': '/icons/layout.svg',
  Services: '/icons/briefcase.svg',
  MERN: '/icons/react.svg',
  SaaS: '/icons/cloud.svg',
  Odoo: '/icons/odoo.svg',
  XML: '/icons/xml.svg',
  Linux: '/icons/linux.svg',
  n8n: '/icons/n8n.svg',
  'Gmail API': '/icons/gmail.svg',
  'Groq AI': '/icons/ai.svg',
  JWT: '/icons/jwt.svg',
  SQLAlchemy: '/icons/sqlalchemy.svg',
};
